
title: GeekTOP Новости из мира IT
name: GeekTOP 
description: Новости из мира IT, электроники, технологий, современных гаджетов, и другая актуальная информация

themecolor: '#202225'
imagehome: img/geektop.jpg
url: 'http://geektop.ru'
baseurl: '/' # the subpath of your site, e.g. /blog



plugins: [jekyll-paginate-v2]
category_dir: blog
pagination:
  enabled: true
  per_page: 9
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date' 
  sort_reverse: true
  trail:
    before: 2
    after: 2

exclude: ['node_modules', 'gulpfile.js', 'package.json', '**/*.DS_Store', 'package-lock.json', 'js/common.js', 'npm-debug.log', '**/Thumbs.db', 'libs', 'sass']


soc:
  <li><a href="#"><i class="fa fa-vk"></i></a></li>
  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
  <li><a href="#"><i class="fa fa-odnoklassniki"></i></a></li>
  <li><a href="#"><i class="fa fa-instagram"></i></a></li>
  <li><a href="#"><i class="fa fa-rss"></i></a></li>

copyright: Копирование контента и размещение на других сайтах запрещено   

